### ISSUE TITLE
Comments: Traefik on Docker for Web Developers

### ISSUE THREAD

**Issue by jtreminio** [jtreminio/jtreminio.com#13]
https://jtreminio.com/blog/traefik-on-docker-for-web-developers/

**Comment by Lemmork** [comment]
Hi, thanks for this great post, which works fine for my http connection.
I'm wondering if I can have http and https on .localhost.
I tried some label settings like this to access my container on port 80 and 443:
```
      - traefik.docker.network=traefik_webgateway
      - traefik.app.frontend.rule=Host:project.localhost
      - traefik.app.backend=web-http
      - traefik.port=80
      - traefik.frontend.entryPoints=http
      - traefik.https.frontend.rule=Host:project.localhost
      - traefik.https.port=443
      - traefik.https.frontend.entryPoints=https
      - traefik.https.backend=web-https
```
But this does not work. If I try to access https://project.localhost I get an ERR_CONNECTION_RESET in Chrome.
I'm not sure, if chrome does a loopback on https at all, or if I have a misconfiguration in traefik.

**Comment by jtreminio** [comment]
@Lemmork Let's Encrypt will not work on a private (local) hostname unless DNS is pointed to your computer's IP.

In other words, too much hassle. I recommend creating a real subdomain on your project's public website, like `dev.mysite.com`, and creating an SSL cert for that subdomain, then using that cert for local development.

**Comment by Lemmork** [comment]
Finaly I solved it by terminating ssl on treafik with a self-signed certificate.

```
version:  '3.5'

services:
  proxy:
    image: traefik
    command: --api --docker --docker.domain=docker.localhost --defaultentrypoints=http,https --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS:/ssl/localhost.crt,/ssl/localhost.key.pem' --logLevel=DEBUG
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - ./ssl:/ssl
networks:
  webgateway:
    driver: bridge
```
