### ISSUE TITLE
Running Docker Containers as Current Host User

### ISSUE THREAD

**Issue by jtreminio** [jtreminio/jtreminio.com#14]
https://jtreminio.com/blog/running-docker-containers-as-current-host-user/

**Comment by lephleg** [comment]
Great article! I've always got halfway to it. It's nice to use this as a reference.

**Comment by rogerpence** [comment]
Juan--What a great a article and clever solution. I struggled with this for months and can't for the life of me understand why your info isn't part of the Docker docs. I'm now running Docker in my container as my local user and it's great (and it worked the first damn time! Nothing ever does that for me!). Next time you make a trip down from Dallas to San Antonio I'll buy lunch! Thank you, again.

**Comment by jtreminio** [comment]
@dcaballero Unfortunately the ID reassignment needs to happen at the pre-boot stage.

If you simply run a script in a running container that does all the work, it may not have your expected results. Any users currently running a process in the container may experience issues since their user ID would technically no longer exist.

**Comment by jtreminio** [comment]
@edulan @lephleg @rogerpence Thank you all for the kind words! I am glad you may have found some use for this!

**Comment by mangalaman93** [comment]
I was wondering if only mapping the user IDs would work. If the current user belongs to root group, things will work out just fine -
* All the host directories can be modified by the current user from the host
* All the container directories can be accessed and modified by the mapped user inside container

Any problems with this solution?

**Comment by Xerkus** [comment]
I tried all kind of approaches, but when you hop projects you can't really expect to have anything readily available in place. Custom scripting takes time to write and as a contractor you are expected to jump right in from pretty much day one.  
So, I ended up using ` lebokus/bindfs` docker plugin to get access to UID/GID remap provided by fuse fs. It proved to be the most flexible approach.
`sudo docker plugin install lebokus/bindfs`

Here is an excerpt from one of the `docker-compose.yml` I used for local microservices development environment where some microservices were bound to local development forks:
`localdev/docker-compose.yml`
```
version: "3.4"

services:
  clients-service:
    build: ../clients-service
    environment:
      SERVICE_DATABASE_HOST: clients-db
      SERVICE_DATABASE_USER: clients
      SERVICE_DATABASE_PASSWORD:
    ports:
      - "8085:80"
    volumes:
      - clients-service:/app
volumes:
  clients-service:
    driver: lebokus/bindfs:latest
    driver_opts:
      sourcePath: "${PWD}/../clients-service"
      map: "${UID:-1000}/33:@${UID:-1000}/@33"  
```
Best part of this approach is that I do not need to modify images or containers in any way, I can spin up already built image and bind to local files. I can bind any local user to any containerized user id, all at the same time.
As everything else with docker, there are downsides. This plugin uses `sshfs`, which adds some overhead and might not work for windows or mac. This setup is pretty static as it depends on volume provider.  Named volume with mapping options must be created first, before it can be used with `docker run -v`. However, there is new `--mount` syntax that should make usage more convenient, since it will allow to create temporary volumes with `docker run --mount` directly.

**Comment by akorz** [comment]
Hello,

Thank you for great article. I try to modify redis image

```
FROM redis:5.0.1

ARG USER_ID
ARG GROUP_ID

RUN echo "=================="
RUN echo ${USER_ID}:${GROUP_ID}

RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
    userdel -f redis && \
    if getent group redis ; then groupdel redis; fi && \
    groupadd -g ${GROUP_ID} redis && \
    useradd -l -u ${USER_ID} -g redis redis && \
    install -d -m 0755 -o redis -g redis /home/redis && \
    chown -R \
         ${USER_ID}:${GROUP_ID} \
        /home/redis \
        /data \
;fi
        
USER redis
```

part of my composer file

```
redis:
    build:
      context: ../redis
      dockerfile: Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    working_dir: /app/redis
    container_name: mrktplc_redis
    command: redis-server --appendonly yes
    volumes:
      - ../data/redis:/data
```

I start it by shell script

```
export USER_ID=$(id -u)
export GROUP_ID=$(id -g)

docker-compose -p mrktplc -f $DIR/../docker/docker-compose.dev.yml up -d --build --remove-orphans
```

Then I check /data folder on my host 

```
root@alexei-Z170-HD3:~/PhpstormProjects/web/data# ls -al
итого 20
drwxr-xr-x  5 alexei alexei 4096 июн 18 18:00 .
drwxr-xr-x 11 alexei alexei 4096 июн 18 17:36 ..
drwxr-xr-x  7     27 sudo   4096 июн 18 18:00 mysql
drwxr-xr-x  5 alexei alexei 4096 июн 18 18:00 rabbitmq
drwxr-xr-x  2 root   root   4096 июн 18 18:00 redis
```

Why do I get redis under root? My current user is 1000:1000

**Comment by jtreminio** [comment]
@akorz If you share a directory with a container, and the directory did not exist before running the docker command, docker creates the directory as the user running the daemon (usually root).

**Comment by Carsak** [comment]
@jtreminio 
Hi Juan.
I just translated your article to russian with my some improvements. Do you mind?
link to article https://almat.su/docker-zapusk-protsessa-iz-pod-tekushhego-polzovatelya/

**Comment by jtreminio** [comment]
> @jtreminio
> Hi Juan.
> I just translated your article to russian with my some improvements. Do you mind?
> link to article https://almat.su/docker-zapusk-protsessa-iz-pod-tekushhego-polzovatelya/

Awesome!

**Comment by musiro77** [comment]
Hello thanks a lot
 unfortuanatly i still have th eproble after running the compose, the mount volume remains by root 0:0

**Comment by musiro77** [comment]
Hi, thanks for this apporach and clarification , however I still see a problem if we mount a volume
.
the folder **/home/sel/features** is always owner by root 0:0 after mounting this volum from host.
see in composer file :  **./temp:/home/sel/features** 
when I remove this line (without mounting), then the folder  /home/sel/features is owned by 1000:1000

here my compose file:
-----------------------

tests:
    container_name: tests
    build:
      context: /.
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    volumes:
       - ./temp:/home/sel/features 
   
in Dockerfile, I am using your approach
the entry point is just ls -Ian
ENTRYPOINT pwd && ls -lan && ls -lan features
-----------

/home/sel
tests       | total 183292
tests       | drwxr-xr-x 1 1000 1000      4096 Nov 18 09:02 .
tests       | drwxr-xr-x 1    0    0      4096 Nov 18 08:53 ..
tests       | -rw-rw-rw- 1 1000 1000      1096 Nov 18 09:02 Dockerfile
**tests       | drwxr-xr-x 2    0    0      4096 Nov 17 13:56 features**
tests       | drwxrwxrwx 1 1000 1000      4096 Nov 18 07:05 huhu
tests       | -rw-rw-rw- 1 1000 1000      8733 Nov 18 07:05 pom.xml

**Comment by carlfischerjba** [comment]
Thanks for a comprehensive write-up of the issues and solutions.

It seems that for your solution to work the id for the internal user account defined at build time needs to match the id for the host account used at run time. This is fine if you're building and running on the same machine but won't necessarily work if you're using different machines, e.g. building the image on a CI server but running on a developer's workstation, possibly in a different company or with a different Linux distribution. Would you agree that this is a concern or have I missed something?

**Comment by jagooch** [comment]
I'm going to use this for strategy for a docker container I'm building to run ansible playbooks that have a lot of dependencies. The problems to solved were keeping ssh keys secure and developing the container on Mac but running it on Linux in production. Having Ansible run as the current user and using ssh keys  on the host machines saves me having to make a service user and giving it ssh keys and access to our servers. 

I'll need to do that later once I move manual processes into pipelines ( like Jenkins ) , but that's a problem to be solved another day :)

**Comment by rajasyedtw** [comment]
@jtreminio - You saved our day!! let me know if you are visiting Tamil Nadu, India. I'll buy Briyani for you!!! :)

After so many attempts/google searches, your blog gave us proper guidelines on how to solve the issue.

**Comment by prismplex** [comment]
Hi,
thank you for this great article with a straight forward solution. Unfortunately I cannot get it to work and I really do not know what the problem could be. It seems to be a permission problem, spinning up the default image(/container) without modifications works.

I'm getting the following error, when I start the container:
```
Traceback (most recent call last):
  File "/sbin/my_init", line 414, in <module>
    main(args)
  File "/sbin/my_init", line 330, in main
    import_envvars(False, False)
  File "/sbin/my_init", line 90, in import_envvars
    for envfile in listdir("/etc/container_environment"):
  File "/sbin/my_init", line 74, in listdir
    return sorted(os.listdir(path))
PermissionError: [Errno 13] Permission denied: '/etc/container_environment'
```

My `Dockerfile`:
```
FROM jtreminio/php:7.3

ARG USER_ID
ARG GROUP_ID

RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
    userdel -f www-data &&\
    if getent group www-data ; then groupdel www-data; fi &&\
    groupadd -g ${GROUP_ID} www-data &&\
    useradd -l -u ${USER_ID} -g www-data www-data &&\
    install -d -m 0755 -o www-data -g www-data /home/www-data &&\
    chown --changes --silent --no-dereference --recursive \
          --from=33:33 ${USER_ID}:${GROUP_ID} \
        /home/www-data \
        /.composer \
        /var/run/php-fpm \
        /var/lib/php/sessions \
;fi
        
USER www-data
```

My `docker-compose.yml`:
```
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: php-memcached

    redis:
      image: redis:alpine
      container_name: php-redis

    php-fpm:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          USER_ID: 1000
          GROUP_ID: 985
      container_name: php-73
      volumes:
        - ${USERDIR}/nginx:/var/www
        - ${USERDIR}/.composer:/.composer
        - ./php-ini-overrides.ini:/etc/php/php-custom.ini
      environment:
        - PHP_INI_SCAN_DIR=:/p/apcu:/p/geoip:/p/imagick:/p/memcached:/p/redis
      ports:
       - "9003:9000"
```

`${USERDIR}` is defined in `etc/environment`.
